kind: Deployment
apiVersion: apps/v1
metadata:
  name: java-cti
  namespace: local-test
  labels:
    app: java-cti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-cti
  template:
    metadata:
      labels:
        app: java-cti
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: duyan-nas
          persistentVolumeClaim:
            claimName: duyan-nas
      containers:
        - name: java-cti
          image: 'local-harbor.duyansoft.com/localcti/cti:test-X'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '4'
              memory: 8Gi
            requests:
              cpu: '1'
              memory: 2Gi
          volumeMounts:
            - name: duyan-nas
              mountPath: /nas
              #livenessProbe:
              #tcpSocket:
              #port: 8080
              #periodSeconds: 30
          startupProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 10
            periodSeconds: 30
