apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: duyan-nas
  namespace: local-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 20Gi
