# application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: duyan-cti
  namespace: argocd
spec:
  project: duyan

  source:
    repoURL: https://github.com/huyinjie889/argocd-lab.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: duyan

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
